### ISSUE TITLE
SQID dump and get links on Property P4159

### ISSUE THREAD

**Issue by salgo60** [Wikidata/SQID#125] opened 2017-08-16 10:09 UTC
I am introducing SQID to people at WeRelate would be nice to get a new dump so the value of P4159 is clickable example Q202266

**Comment by mmarx** [comment] 2017-08-16 12:20
This is a duplicate of #114.

**Comment by mkroetzsch** [comment] 2017-08-17 10:40
Fixed by recent data update (requires reload, possibly hard reload).

**Comment by salgo60** [comment] 2018-04-02 06:14
Could we get a new reload I 
https://tools.wmflabs.org/sqid/#/view?id=Q4935959&lang=en

P4819 is not clickable

**Comment by mmarx** [comment] 2019-08-12 15:46
Fixed.

**Closed by mmarx** 2019-08-12 15:46 UTC
Labels: duplicate
